# Generated by Django 4.1.3 on 2023-11-07 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EMA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('signals', models.JSONField()),
                ('xirr', models.DecimalField(decimal_places=4, max_digits=10)),
                ('profit', models.IntegerField()),
                ('period', models.PositiveIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferencfinance.stock')),
            ],
            options={
                'verbose_name': 'EMA Period',
                'verbose_name_plural': 'EMA Periods',
                'ordering': ['period'],
            },
        ),
    ]
