# Generated by Django 4.1.3 on 2024-01-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferencfinance', '0004_ema_cashflows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ema',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
